// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RematadosWeb.Context;

namespace RematadosWeb.Migrations
{
    [DbContext(typeof(RematadosDatabaseContext))]
    [Migration("20220711000234_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RematadosWeb.Models.Articulo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<int?>("CompradorDni")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int?>("VendedorDni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompradorDni");

                    b.HasIndex("VendedorDni");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("RematadosWeb.Models.ItemCarrito", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticuloId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioDni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UsuarioDni");

                    b.ToTable("ItemCarritos");
                });

            modelBuilder.Entity("RematadosWeb.Models.Mensaje", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticuloId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fechahora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioDni")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("UsuarioDni");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("RematadosWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Dni");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RematadosWeb.Models.Articulo", b =>
                {
                    b.HasOne("RematadosWeb.Models.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorDni");

                    b.HasOne("RematadosWeb.Models.Usuario", "Vendedor")
                        .WithMany()
                        .HasForeignKey("VendedorDni");
                });

            modelBuilder.Entity("RematadosWeb.Models.ItemCarrito", b =>
                {
                    b.HasOne("RematadosWeb.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId");

                    b.HasOne("RematadosWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioDni");
                });

            modelBuilder.Entity("RematadosWeb.Models.Mensaje", b =>
                {
                    b.HasOne("RematadosWeb.Models.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("ArticuloId");

                    b.HasOne("RematadosWeb.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioDni");
                });
#pragma warning restore 612, 618
        }
    }
}
